openapi: 3.0.3
info:
  title: TouchYatra Apis Docs
  description: >-
    # TouchYatra.app
  version: 1.3.1
  contact: {}
servers:
  - url: ${{server}}
paths: 
  /check:
    get:
      tags:
        - Health Check
      summary: Check API status
      description: Check if the API is up and running
      operationId: checkApiStatus
      responses:
        '200':
          description: API is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "API is up and running"